/**
 * Auto-registers all filled icons into the icon registry.
 * This file is imported by the Icons barrel (index.ts) to ensure
 * the filled set is populated alongside the outlined set.
 */

import { registerIcons } from './registry';
import {
  IconHomeFilled,
  IconMenuFilled,
  IconSearchFilled,
  IconArrowLeftFilled,
  IconArrowRightFilled,
  IconChevronDownFilled,
  IconChevronUpFilled,
  IconChevronRightFilled,
  IconPlusFilled,
  IconMinusFilled,
  IconXFilled,
  IconCheckFilled,
  IconEditFilled,
  IconTrashFilled,
  IconDownloadFilled,
  IconUploadFilled,
  IconInfoFilled as IconInfoFilledComp,
  IconAlertCircleFilled,
  IconCheckCircleFilled,
  IconXCircleFilled,
  IconFileFilled,
  IconFolderFilled,
  IconUserFilled,
  IconCalendarFilled,
  IconSettingsFilled,
  IconFilterFilled,
  IconSortFilled,
  IconGridFilled,
  IconListFilled,
  IconMoreHorizontalFilled,
} from './sets/filled/FilledIcons';

registerIcons('filled', {
  Home: IconHomeFilled,
  Menu: IconMenuFilled,
  Search: IconSearchFilled,
  ArrowLeft: IconArrowLeftFilled,
  ArrowRight: IconArrowRightFilled,
  ChevronDown: IconChevronDownFilled,
  ChevronUp: IconChevronUpFilled,
  ChevronRight: IconChevronRightFilled,
  Plus: IconPlusFilled,
  Minus: IconMinusFilled,
  X: IconXFilled,
  Check: IconCheckFilled,
  Edit: IconEditFilled,
  Trash: IconTrashFilled,
  Download: IconDownloadFilled,
  Upload: IconUploadFilled,
  Info: IconInfoFilledComp,
  AlertCircle: IconAlertCircleFilled,
  CheckCircle: IconCheckCircleFilled,
  XCircle: IconXCircleFilled,
  File: IconFileFilled,
  Folder: IconFolderFilled,
  User: IconUserFilled,
  Calendar: IconCalendarFilled,
  Settings: IconSettingsFilled,
  Filter: IconFilterFilled,
  Sort: IconSortFilled,
  Grid: IconGridFilled,
  List: IconListFilled,
  MoreHorizontal: IconMoreHorizontalFilled,
});
