/**
 * Auto-registers all outlined icons from Icons.tsx into the icon registry.
 * This file is imported by the Icons barrel (index.ts) to ensure
 * the outlined set is always populated.
 */

import { registerIcons } from './registry';
import {
  IconHome,
  IconMenu,
  IconSidebarOpen,
  IconSidebarClose,
  IconSearch,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronDown,
  IconExternalLink,
  IconPlus,
  IconMinus,
  IconX,
  IconCheck,
  IconEdit,
  IconTrash,
  IconCopy,
  IconDownload,
  IconUpload,
  IconShare,
  IconSave,
  IconRefresh,
  IconInfo,
  IconAlertCircle,
  IconAlertTriangle,
  IconCheckCircle,
  IconXCircle,
  IconLoader,
  IconFile,
  IconFolder,
  IconImage,
  IconUser,
  IconUsers,
  IconCalendar,
  IconClock,
  IconSettings,
  IconEye,
  IconEyeOff,
  IconLock,
  IconUnlock,
  IconPlay,
  IconPause,
  IconVolume,
  IconVolumeOff,
  IconFilter,
  IconSort,
  IconMaximize,
  IconMinimize,
  IconMoreHorizontal,
  IconMoreVertical,
  IconGrid,
  IconList,
  IconDrag,
  IconCart,
  IconApps,
  IconProduct,
  IconBundle,
  IconIntegration,
  IconStar,
  IconHeart,
  IconThumbsUp,
  IconThumbsDown,
  IconMail,
  IconBell,
  IconMessageCircle,
  IconColors,
  IconTypography,
  IconSpacing,
  IconRadius,
  IconShadows,
  IconBreakpoints,
  IconAvatar,
  IconButton,
  IconTab,
  IconBanner,
  IconFoundations,
  IconComponents,
  IconIcons,
  IconBadge,
  IconLayoutCard,
  IconListItem,
  IconStepper,
  IconLeftNav,
  IconStatusComplete,
  IconStatusInProgress,
  IconStatusNotStarted,
  IconStatusDisabled,
  IconDataTable,
} from './Icons';

registerIcons('outlined', {
  Home: IconHome,
  Menu: IconMenu,
  SidebarOpen: IconSidebarOpen,
  SidebarClose: IconSidebarClose,
  Search: IconSearch,
  ArrowLeft: IconArrowLeft,
  ArrowRight: IconArrowRight,
  ArrowUp: IconArrowUp,
  ArrowDown: IconArrowDown,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronUp: IconChevronUp,
  ChevronDown: IconChevronDown,
  ExternalLink: IconExternalLink,
  Plus: IconPlus,
  Minus: IconMinus,
  X: IconX,
  Check: IconCheck,
  Edit: IconEdit,
  Trash: IconTrash,
  Copy: IconCopy,
  Download: IconDownload,
  Upload: IconUpload,
  Share: IconShare,
  Save: IconSave,
  Refresh: IconRefresh,
  Info: IconInfo,
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  CheckCircle: IconCheckCircle,
  XCircle: IconXCircle,
  Loader: IconLoader,
  File: IconFile,
  Folder: IconFolder,
  Image: IconImage,
  User: IconUser,
  Users: IconUsers,
  Calendar: IconCalendar,
  Clock: IconClock,
  Settings: IconSettings,
  Eye: IconEye,
  EyeOff: IconEyeOff,
  Lock: IconLock,
  Unlock: IconUnlock,
  Play: IconPlay,
  Pause: IconPause,
  Volume: IconVolume,
  VolumeOff: IconVolumeOff,
  Filter: IconFilter,
  Sort: IconSort,
  Maximize: IconMaximize,
  Minimize: IconMinimize,
  MoreHorizontal: IconMoreHorizontal,
  MoreVertical: IconMoreVertical,
  Grid: IconGrid,
  List: IconList,
  Drag: IconDrag,
  Cart: IconCart,
  Apps: IconApps,
  Product: IconProduct,
  Bundle: IconBundle,
  Integration: IconIntegration,
  Star: IconStar,
  Heart: IconHeart,
  ThumbsUp: IconThumbsUp,
  ThumbsDown: IconThumbsDown,
  Mail: IconMail,
  Bell: IconBell,
  MessageCircle: IconMessageCircle,
  Colors: IconColors,
  Typography: IconTypography,
  Spacing: IconSpacing,
  Radius: IconRadius,
  Shadows: IconShadows,
  Breakpoints: IconBreakpoints,
  Avatar: IconAvatar,
  Button: IconButton,
  Tab: IconTab,
  Banner: IconBanner,
  Foundations: IconFoundations,
  Components: IconComponents,
  Icons: IconIcons,
  Badge: IconBadge,
  LayoutCard: IconLayoutCard,
  ListItem: IconListItem,
  Stepper: IconStepper,
  LeftNav: IconLeftNav,
  StatusComplete: IconStatusComplete,
  StatusInProgress: IconStatusInProgress,
  StatusNotStarted: IconStatusNotStarted,
  StatusDisabled: IconStatusDisabled,
  DataTable: IconDataTable,
});
