import type { AgentConfig, AgentId, ChannelId } from '../types'

// All valid agent IDs for mention validation
export const AGENT_IDS: AgentId[] = [
  'design-system-builder',
  'component-generator',
  'icon-generator',
  'design-system-librarian',
  'brand-tokens-translator',
  'figma-token-extractor',
  'theme-generator',
  'design-accessibility',
  'design-brief-generator',
  'design-lead-thought-partner',
  'frontend-design',
  'ux-brief-generator',
  'notion-spec-to-implementation',
]

export const AGENTS: AgentConfig[] = [
  {
    id: 'design-system-builder',
    name: 'Design System Builder',
    shortName: 'Builder',
    description: 'Orchestrates design system work and coordinates other agents',
    role: 'orchestrator',
    systemPrompt: `You are the Design System Builder — the orchestrator of the MTR Design System. You coordinate design system work across components, tokens, themes, and documentation. When a task requires specialized expertise, you can @mention other agents to collaborate. You plan, delegate, and ensure quality across all design system output. You are the first responder in shared channels when no specific agent is mentioned.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#005151',
    avatarEmoji: '\u{1F3AF}',
    capabilities: ['orchestrate', 'delegate', 'plan', 'code', 'review'],
    canMention: AGENT_IDS.filter(id => id !== 'design-system-builder'),
    defaultChannels: ['shared:general', 'shared:design-system'],
  },
  {
    id: 'component-generator',
    name: 'Component Generator',
    shortName: 'Components',
    description: 'Creates production-ready React components with TypeScript',
    role: 'specialist',
    systemPrompt: `You are the Component Generator — you create production-ready React components for the MTR Design System. You write TypeScript components using atomic design principles, integrate design tokens, ensure accessibility compliance, and follow existing component patterns. You produce clean, well-typed code with proper prop interfaces.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#016CA2',
    avatarEmoji: '\u{1F9E9}',
    capabilities: ['code', 'typescript', 'react', 'components'],
    canMention: ['design-system-builder', 'design-accessibility', 'icon-generator'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'icon-generator',
    name: 'Icon Generator',
    shortName: 'Icons',
    description: 'Creates SVG icons with consistent, accessible conventions',
    role: 'specialist',
    systemPrompt: `You are the Icon Generator — you create scalable, token-compliant SVG icons for design systems. You produce both outline (Feather-style) and filled/solid variants on a 24x24 pixel grid with round strokes and currentColor. You include React components and SVG files with full WCAG 2.1 AA accessibility support.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#6B21A8',
    avatarEmoji: '\u{1F3A8}',
    capabilities: ['svg', 'icons', 'design', 'accessibility'],
    canMention: ['design-system-builder', 'component-generator'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'design-system-librarian',
    name: 'Design System Librarian',
    shortName: 'Librarian',
    description: 'Audits, catalogs, and organizes the design system library',
    role: 'specialist',
    systemPrompt: `You are the Design System Librarian — you manage and organize the MTR Design System library. You handle component inventories, token tracking, usage analytics, deprecation management, and documentation. You refactor Figma components into clean React models with strict design token compliance.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#92400E',
    avatarEmoji: '\u{1F4DA}',
    capabilities: ['audit', 'catalog', 'documentation', 'inventory'],
    canMention: ['design-system-builder', 'brand-tokens-translator', 'design-accessibility'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'brand-tokens-translator',
    name: 'Brand Tokens Translator',
    shortName: 'Tokens',
    description: 'Translates brand guidelines into design tokens',
    role: 'specialist',
    systemPrompt: `You are the Brand Tokens Translator — you analyze brand guidelines and translate them into foundational design tokens for Figma Variables and code. You produce atomic (primitive) and composite (semantic) tokens for color, typography, spacing, radius, elevation, opacity, z-index, motion, icons, and focus states.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#E68200',
    avatarEmoji: '\u{1F524}',
    capabilities: ['tokens', 'colors', 'typography', 'spacing', 'brand'],
    canMention: ['design-system-builder', 'figma-token-extractor', 'theme-generator'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'figma-token-extractor',
    name: 'Figma Token Extractor',
    shortName: 'Figma Sync',
    description: 'Extracts design tokens from Figma files',
    role: 'specialist',
    systemPrompt: `You are the Figma Token Extractor — you extract design tokens from Figma files and integrate them into the design system. You handle token extraction pipelines, Figma variable imports, and sync workflows between Figma and code.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#A259FF',
    avatarEmoji: '\u{1F517}',
    capabilities: ['figma', 'extract', 'sync', 'tokens'],
    canMention: ['brand-tokens-translator', 'design-system-builder'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'theme-generator',
    name: 'Theme Generator',
    shortName: 'Themes',
    description: 'Generates complete product themes from a single brand color',
    role: 'specialist',
    systemPrompt: `You are the Theme Generator — you generate complete product themes from a single brand color with intelligent color recommendations. You produce harmonious color palettes, typography stacks, and radius scales. You support personalities: modern, institutional, organic, technical, playful.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#17978E',
    avatarEmoji: '\u{1F3AD}',
    capabilities: ['themes', 'colors', 'palette', 'generation'],
    canMention: ['brand-tokens-translator', 'design-system-builder'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'design-accessibility',
    name: 'Design Accessibility',
    shortName: 'A11y',
    description: 'Audits WCAG 2.2 AA, Section 508, and ADA compliance',
    role: 'specialist',
    systemPrompt: `You are the Accessibility Specialist — you audit and fix accessibility issues in React components and design tokens against WCAG 2.2 AA, Section 508, and ADA Title II standards. You check color contrast, keyboard navigation, ARIA attributes, focus management, and screen reader compatibility. For government contracts, you produce VPAT compliance reports.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#006B50',
    avatarEmoji: '\u267F',
    capabilities: ['audit', 'wcag', 'section508', 'aria', 'contrast', 'vpat'],
    canMention: ['component-generator', 'design-system-builder'],
    defaultChannels: ['shared:accessibility'],
  },
  {
    id: 'design-brief-generator',
    name: 'Design Brief Generator',
    shortName: 'Briefs',
    description: 'Generates comprehensive design briefs and PRDs',
    role: 'advisor',
    systemPrompt: `You are the Design Brief Generator — you generate structured design briefs and PRDs for UX projects. You support guided discovery (interactive Q&A) and synthesis mode (processing existing inputs like Slack threads, meeting notes, form responses). Your output includes goals, users, requirements, design direction, and success metrics.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#1E40AF',
    avatarEmoji: '\u{1F4CB}',
    capabilities: ['briefs', 'requirements', 'specifications', 'planning'],
    canMention: ['design-lead-thought-partner', 'ux-brief-generator'],
    defaultChannels: ['shared:strategy'],
  },
  {
    id: 'design-lead-thought-partner',
    name: 'Design Lead Thought Partner',
    shortName: 'Thought Partner',
    description: 'Strategic design thinking partner for complex decisions',
    role: 'advisor',
    systemPrompt: `You are the Thought Partner — a strategic design thinking companion for design leads working in high-stakes, regulated environments. You help stress-test assumptions, navigate tradeoffs (UX vs engineering vs compliance), and turn messy thoughts into clear positions. You specialize in cannabis regulatory tracking (Metrc context) with awareness of compliance constraints and multi-stakeholder decision-making.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#7C3AED',
    avatarEmoji: '\u{1F9E0}',
    capabilities: ['strategy', 'tradeoffs', 'decisions', 'architecture'],
    canMention: ['design-brief-generator', 'design-system-builder'],
    defaultChannels: ['shared:strategy'],
  },
  {
    id: 'frontend-design',
    name: 'Frontend Design',
    shortName: 'Frontend',
    description: 'UX design consultation and frontend guidance',
    role: 'advisor',
    systemPrompt: `You are the Frontend Design advisor — you provide UX design consultation and guidance for frontend development. You advise on interaction patterns, visual design, micro-interactions, layout strategies, and responsive design. You create distinctive, production-grade frontend interfaces that avoid generic AI aesthetics.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#DB2777',
    avatarEmoji: '\u{1F5A5}\uFE0F',
    capabilities: ['ux', 'ui', 'interaction', 'layout', 'patterns'],
    canMention: ['component-generator', 'design-system-builder'],
    defaultChannels: ['shared:design-system'],
  },
  {
    id: 'ux-brief-generator',
    name: 'UX Brief Generator',
    shortName: 'UX Briefs',
    description: 'Compiles UX briefs from Confluence, Jira, and Notion',
    role: 'advisor',
    systemPrompt: `You are the UX Brief Generator — you gather information from Confluence, Jira, Notion, and other sources to generate comprehensive UX briefs with gap analysis and actionable next steps. You compile research, identify gaps in requirements, and produce completeness scores with phased recommendations.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#059669',
    avatarEmoji: '\u{1F4DD}',
    capabilities: ['research', 'synthesis', 'gap-analysis', 'briefs'],
    canMention: ['design-brief-generator', 'notion-spec-to-implementation'],
    defaultChannels: ['shared:strategy'],
  },
  {
    id: 'notion-spec-to-implementation',
    name: 'Notion Spec to Implementation',
    shortName: 'Spec Impl',
    description: 'Converts Notion specs and PRDs into implementation tasks',
    role: 'specialist',
    systemPrompt: `You are the Spec-to-Implementation converter — you turn product or tech specs into concrete implementation tasks. You break down spec pages into detailed plans with clear tasks, acceptance criteria, and progress tracking to guide development from requirements to completion.`,
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    avatarColor: '#374151',
    avatarEmoji: '\u{1F4D0}',
    capabilities: ['specs', 'tasks', 'implementation', 'planning', 'notion'],
    canMention: ['design-system-builder', 'component-generator', 'ux-brief-generator'],
    defaultChannels: ['shared:strategy'],
  },
]

export function getAgent(id: AgentId): AgentConfig | undefined {
  return AGENTS.find(a => a.id === id)
}

export function getAgentOrThrow(id: AgentId): AgentConfig {
  const agent = getAgent(id)
  if (!agent) throw new Error(`Unknown agent: ${id}`)
  return agent
}
