// =============================================================================
// Accessibility Compliance Dashboard — Type Definitions
// =============================================================================

export type Severity = 'critical' | 'serious' | 'moderate' | 'minor'
export type IssueStatus = 'open' | 'in-progress' | 'resolved'
export type WCAGLevel = 'A' | 'AA'
export type WCAGCategory = 'Perceivable' | 'Operable' | 'Understandable' | 'Robust'
export type Effort = 'low' | 'medium' | 'high'
export type ComplianceStatus = 'compliant' | 'needs-remediation' | 'critical'

// -----------------------------------------------------------------------------
// WCAG Knowledge Base Types
// -----------------------------------------------------------------------------

export interface RemediationPattern {
  issueType: string
  fix: string
  codeExample: string
  effort: Effort
  testingSteps: string[]
}

export interface WCAGCriterionInfo {
  code: string
  name: string
  level: WCAGLevel
  category: WCAGCategory
  requirement: string
  commonPatterns: RemediationPattern[]
  documentationUrls: DocumentationLink[]
}

// -----------------------------------------------------------------------------
// Issue Analysis (generated by analyze.ts)
// -----------------------------------------------------------------------------

export interface IssueAnalysis {
  wcagRequirement: string
  wcagLevel: WCAGLevel
  category: WCAGCategory
  estimatedEffort: Effort
  remediationPattern: string
  codeExample: string
  testingSteps: string[]
  relatedCriteria: string[]
  documentationUrls: DocumentationLink[]
}

export interface DocumentationLink {
  label: string
  url: string
}

// -----------------------------------------------------------------------------
// VPAT Report Data
// -----------------------------------------------------------------------------

export interface VPATIssue {
  id: string
  title: string
  severity: Severity
  wcagCriteria: string[]
  location: string
  currentState: string
  requiredState: string
  impact: string
  codeRecommendation?: string
  remediationPhase: 1 | 2 | 3
  status: IssueStatus
  analysis?: IssueAnalysis
}

export interface VPATReport {
  id: string
  stateCode: string
  auditDate: string
  standard: string
  auditor: string
  scope: string[]
  issues: VPATIssue[]
  passedChecks: string[]
  overallStatus: ComplianceStatus
  sourceFileName: string
  importedAt: string
}

// -----------------------------------------------------------------------------
// State Compliance Tracking
// -----------------------------------------------------------------------------

export interface StateCompliance {
  stateCode: string
  stateName: string
  reports: VPATReport[]
  latestScore: number
  openIssues: number
  criticalCount: number
  lastAuditDate: string | null
}

// -----------------------------------------------------------------------------
// Analysis Output Types
// -----------------------------------------------------------------------------

export interface CommonFailure {
  wcagCriterion: string
  criterionName: string
  occurrences: number
  states: string[]
  severity: Severity
  topRemediation: string
}

export interface ComplianceSummary {
  stateCode: string
  stateName: string
  score: number
  totalIssues: number
  bySeverity: Record<Severity, number>
  byCategory: Record<WCAGCategory, number>
  topFixes: Array<{ issue: VPATIssue; impact: number }>
  passedChecks: number
  lastAuditDate: string | null
}

// -----------------------------------------------------------------------------
// Store Interface
// -----------------------------------------------------------------------------

export interface ComplianceStore {
  states: StateCompliance[]
  isLoaded: boolean
  addState: (code: string, name: string) => void
  removeState: (code: string) => void
  addReport: (stateCode: string, report: VPATReport) => void
  removeReport: (stateCode: string, reportId: string) => void
  updateIssueStatus: (stateCode: string, reportId: string, issueId: string, status: IssueStatus) => void
}
