/**
 * Earth Product Theme
 * Generated by Prism Theme Playground on 2026-03-22
 *
 * Brand color: #342f2d
 * Accent color: #4A6D6C
 */

import type { ProductTheme } from './theme-interface';
import { buildBorderRadius, buildComponentRadius } from './theme-interface';

export const earthTheme: ProductTheme = {
  name: 'Earth',
  colors: {
    brand: {
      default: '#342f2d',
      darker: '#0e0c0b',
      lighter: '#5e5e5e',
    },
    accent: {
      default: '#4A6D6C',
      darker: '#2F4847',
      lighter: '#6B8F8E',
    },
    surface: {
      light: '#fdf9f7',
      lightDarker: '#f4efec',
      dark: '#38302C',
      darkDarker: '#2D2520',
      disabled: {
        onLight: 'rgba(0, 0, 0, 0.03)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      info: '#d8e1ee',
      success: '#d5ebd5',
      warning: '#e1d8c1',
      important: '#f5e6e6',
    },
    surfaceBorder: {
      info: '#E0E4EB',
      success: '#DCE8DC',
      warning: '#e1d8c1',
      important: '#EBD0D4',
    },
    text: {
      highEmphasis: {
        onLight: '#241E1B',
        onDark: '#FFFFFF',
      },
      lowEmphasis: {
        onLight: '#544A45',
        onDark: '#B3B3B3',
      },
      disabled: {
        onLight: 'rgba(0, 0, 0, 0.30)',
        onDark: 'rgba(255, 255, 255, 0.30)',
      },
      action: {
        enabled: '#463A34',
        hover: '#2D2520',
        active: '#241E1B',
      },
      success: '#4A6E4A',
      warning: '#8B7040',
      important: '#A63A3A',
    },
    border: {
      lowEmphasis: {
        onLight: 'rgba(0, 0, 0, 0.10)',
        onDark: 'rgba(255, 255, 255, 0.10)',
        hover: {
          onLight: 'rgba(0, 0, 0, 0.27)',
          onDark: 'rgba(255, 255, 255, 0.27)',
        },
      },
      midEmphasis: {
        onLight: 'rgba(0, 0, 0, 0.15)',
        onDark: 'rgba(255, 255, 255, 0.15)',
      },
      highEmphasis: {
        onLight: 'rgba(0, 0, 0, 0.42)',
        onDark: 'rgba(255, 255, 255, 0.43)',
      },
    },
    icon: {
      enabled: { onLight: 'rgba(0, 0, 0, 0.55)', onDark: 'rgba(255, 255, 255, 0.94)' },
      hover: { onLight: 'rgba(0, 0, 0, 0.65)' },
      active: { onLight: 'rgba(0, 0, 0, 0.75)' },
      selected: { onLight: 'rgba(0, 0, 0, 0.85)' },
      disabled: { onLight: 'rgba(0, 0, 0, 0.20)', onDark: 'rgba(255, 255, 255, 0.20)' },
      lowEmphasis: { enabled: { onLight: 'rgba(0, 0, 0, 0.43)', onDark: 'rgba(255, 255, 255, 0.65)' } },
    },
    iconBg: {
      info: '#E0E4EB',
      info_onDark: 'rgba(122, 145, 255, 0.25)',
      success: '#DCE8DC',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#e1d8c1',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#EBD0D4',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },
    action: {
      enabled: '#463A34',
      hover: '#2D2520',
      active: '#241E1B',
      important: {
        enabled: '#A63A3A',
        hover: '#8F2E2E',
        active: '#752020',
      },
      monochrome: {
        onLight: {
          enabled: 'rgba(0, 0, 0, 0.55)', hover: 'rgba(0, 0, 0, 0.65)',
          active: 'rgba(0, 0, 0, 0.75)', selected: 'rgba(0, 0, 0, 0.85)',
          disabled: 'rgba(0, 0, 0, 0.20)', bg: 'rgba(0, 0, 0, 0.08)',
          lowEmphasis: { enabled: 'rgba(0, 0, 0, 0.43)' },
        },
        onDark: {
          enabled: 'rgba(255, 255, 255, 0.94)', hover: 'rgba(255, 255, 255, 1)',
          active: 'rgba(255, 255, 255, 1)', selected: 'rgba(255, 255, 255, 1)',
          disabled: 'rgba(255, 255, 255, 0.20)', bg: 'rgba(255, 255, 255, 0.09)',
          lowEmphasis: { enabled: 'rgba(255, 255, 255, 0.65)' },
        },
      },
    },
    status: {
      info: '#5f72bf',
      info_onDark: 'rgba(122, 145, 255, 0.25)',
      success: '#4A6E4A',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#8B7040',
      warningLight: '#e1d8c1',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#A63A3A',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },
    badge: {
      info: '#3f4b73', infoLight: '#E0E4EB',
      success: '#4A6E4A', successLight: '#DCE8DC',
      warning: '#8B7040', warningLight: '#e1d8c1',
      important: '#A63A3A', importantLight: '#EBD0D4',
      aqua: '#4A6D6C', aquaLight: '#6B8F8E',
      green: '#4A6E4A', greenLight: '#DCE8DC',
      yellow: '#8B7040', yellowLight: '#e1d8c1',
      fuschia: '#CF26B8', fuschiaLight: '#FCCFF6',
      purple: '#A14CE1', purpleLight: '#EDDCF9',
      charcoal: '#38302C', charcoalLight: '#f4efec',
    },
    avatar: {
      '01': '#D6EAFF', '02': '#FFDBFA', '03': '#EFE0FF', '04': '#CFEFC2',
      '05': '#BEF4ED', '06': '#FFE68F', '07': '#FFE3DB', '08': '#FFE2C2',
    },
    dataViz: {
      border: '#241E1B',
      '01': '#001446', '02': '#062E69', '03': '#094A8D', '04': '#0068B2',
      '05': '#0094BE', '06': '#37B9B2', '07': '#9FD7AB', '08': '#F0F2BD',
      '09': '#F1D89A', '10': '#EFB777', '11': '#ED9461', '12': '#E96959',
      '13': '#C74046', '14': '#95222C', '15': '#660011',
    },
    cvd: {
      blue: '#0072B2', lightBlue: '#56B4E9', yellow: '#F0E442', green: '#009E73',
      orange: '#E69F00', vermillion: '#D55E00', pink: '#CC79A7', charcoal: '#323232',
    },
    hover: { onLight: 'rgba(0, 0, 0, 0.05)', onDark: 'rgba(255, 255, 255, 0.15)' },
    selected: { onLight: 'rgba(0, 0, 0, 0.09)' },
    selectedHighlight: '#E0D6D0',
    selectedHighlight_hover: '#D0C6C0',
    focusBorder: { onLight: '#4A6D6C', onDark: 'rgba(255, 255, 255, 0.65)' },
    scrim: 'rgba(0, 0, 0, 0.32)',
    scrollbar: {
      enabled: { onLight: 'rgba(0, 0, 0, 0.42)', onDark: 'rgba(255, 255, 255, 0.43)' },
      hover: { onLight: 'rgba(0, 0, 0, 0.57)', onDark: 'rgba(255, 255, 255, 0.58)' },
      active: { onLight: 'rgba(0, 0, 0, 0.72)', onDark: 'rgba(255, 255, 255, 0.73)' },
    },
    navItemText: { enabled: { onLight: 'rgba(0, 0, 0, 0.72)', onDark: 'rgba(255, 255, 255, 0.88)' } },
    buttonToggleBg: { onLight: 'rgba(0, 0, 0, 0.08)', onDark: 'rgba(255, 255, 255, 0.08)' },
    chipBg: { enabled: 'rgba(0, 0, 0, 0.08)', hover: 'rgba(0, 0, 0, 0.13)' },
    progressIndicatorTrack: 'rgba(0, 0, 0, 0.15)',
    tableCellHighlight: { highEmphasis: '#5e5e5e', midEmphasis: '#E0D6D0' },
    grid: { finishedRowText: '#544A45', packageIconColor: '#544A45' },
  },
  typography: {
    fontFamilies: {
      display: "'Inter', sans-serif",
      body: "'Nunito Sans', sans-serif",
      mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontWeights: { regular: '400', medium: '500', semibold: '600', bold: '700' },
    scale: {
      lineHeightTight: '1.25',
      lineHeightNormal: '1.6',
      letterSpacingHeading: '-0.3px',
      letterSpacingBody: '0.15px',
    },
  },
  borderRadius: buildBorderRadius(3),
  elevation: {
    none: 'none',
    xs: '0px 1px 2px rgba(70, 58, 52, 0.055)',
    sm: '0px 1px 3px rgba(70, 58, 52, 0.11), 0px 1px 2px rgba(70, 58, 52, 0.066)',
    md: '0px 4px 6px -1px rgba(70, 58, 52, 0.11), 0px 2px 4px -1px rgba(70, 58, 52, 0.066)',
    lg: '0px 10px 15px -3px rgba(70, 58, 52, 0.11), 0px 4px 6px -2px rgba(70, 58, 52, 0.055)',
    xl: '0px 20px 25px -5px rgba(70, 58, 52, 0.11), 0px 10px 10px -5px rgba(70, 58, 52, 0.044)',
    '2xl': '0px 25px 50px -12px rgba(70, 58, 52, 0.275)',
    inner: 'inset 0px 2px 4px rgba(70, 58, 52, 0.07)',
    brand: '0px 4px 14px rgba(52, 47, 45, 0.25)',
    brandLg: '0px 10px 25px rgba(52, 47, 45, 0.3)',
  },
  spacing: {
    unit: '4px',
    inputPadding: '14px',
    buttonPadding: '18px',
    cardPadding: '28px',
    sectionGap: '56px',
    componentGap: '22px',
  },
  iconStyle: {
    set: 'outlined',
    strokeWidth: '1.25',
    cornerStyle: 'round',
    defaultSize: '20',
    overrides: {},
  },
  componentRadius: buildComponentRadius(3, { button: '10px' }),
};
