/**
 * RID Dark Theme
 * Originally generated by /anthropics-theme-factory on 2026-03-04
 *
 * A neutral dark palette paired with RID's design language.
 * Brand accent: #4A9A7E (teal) for brand surfaces, #5AAC90 (bright teal) for text/actions on dark.
 * Surfaces: neutral grays (#1B1B1B → #1F1F1F → #2D2D2D → #3B3B3B)
 *
 * DS components reference `onLight` tokens for their primary surfaces.
 * We map dark values INTO the `onLight` slots so components render dark
 * without any CSS overrides.
 *
 * Design notes:
 * - Brand teal brightened for dark backgrounds (AA contrast on #1F1F1F)
 * - Neutral gray surfaces avoid green tint for true dark mode feel
 * - Header uses surface.dark (#2D2D2D) — not brand green
 * - Status/semantic colors lightened for readability on dark surfaces
 * - Shadows use pure black at higher opacity for dark context depth
 */

import type { ProductTheme } from './theme-interface';
import { buildBorderRadius, buildComponentRadius } from './theme-interface';

export const ridDarkTheme: ProductTheme = {
  name: 'RID-Dark',
  colors: {
    brand: {
      default: '#3B8767',
      darker: '#2D6A50',
      lighter: '#4A9A7E',
    },

    accent: {
      default: '#D4A017',
      darker: '#B8860B',
      lighter: '#E0B840',
    },

    surface: {
      light: '#2D2D2D',
      lightDarker: '#1F1F1F',
      dark: '#1F1F1F',
      darkDarker: '#1B1B1B',
      disabled: {
        onLight: 'rgba(255, 255, 255, 0.05)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      info: 'rgba(60, 120, 180, 0.15)',
      success: 'rgba(90, 172, 144, 0.15)',
      warning: 'rgba(209, 118, 0, 0.15)',
      important: 'rgba(220, 12, 34, 0.15)',
    },

    surfaceBorder: {
      info: '#3E5570',
      success: '#2D5E4D',
      warning: '#6E4A1A',
      important: '#6E2A30',
    },

    text: {
      highEmphasis: {
        onLight: '#FFFFFF',
        onDark: '#FFFFFF',
      },
      lowEmphasis: {
        onLight: '#D1D1D1',
        onDark: 'rgba(255, 255, 255, 0.70)',
      },
      disabled: {
        onLight: 'rgba(255, 255, 255, 0.30)',
        onDark: 'rgba(255, 255, 255, 0.30)',
      },
      action: {
        enabled: '#5AAC90',
        hover: '#6EC4A4',
        active: '#4A9A7E',  // brand.default
      },
      success: '#5AAC90',
      warning: '#E89D3E',
      important: '#F06E7A',
    },

    border: {
      lowEmphasis: {
        onLight: '#787878',
        onDark: 'rgba(255, 255, 255, 0.25)',
        hover: {
          onLight: '#888888',
          onDark: 'rgba(255, 255, 255, 0.40)',
        },
      },
      midEmphasis: {
        onLight: '#888888',
        onDark: 'rgba(255, 255, 255, 0.32)',
      },
      highEmphasis: {
        onLight: '#999999',
        onDark: 'rgba(255, 255, 255, 0.55)',
      },
    },

    icon: {
      enabled: {
        onLight: '#D1D1D1',
        onDark: 'rgba(255, 255, 255, 0.94)',
      },
      hover: {
        onLight: '#E0E0E0',
      },
      active: {
        onLight: '#FFFFFF',
      },
      selected: {
        onLight: '#FFFFFF',
      },
      disabled: {
        onLight: 'rgba(255, 255, 255, 0.20)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      lowEmphasis: {
        enabled: {
          onLight: '#A1A1A1',
          onDark: 'rgba(255, 255, 255, 0.65)',
        },
      },
    },

    iconBg: {
      info: 'rgba(60, 120, 180, 0.20)',
      info_onDark: 'rgba(60, 120, 180, 0.25)',
      success: 'rgba(90, 172, 144, 0.20)',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: 'rgba(230, 130, 0, 0.20)',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: 'rgba(248, 104, 118, 0.20)',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    action: {
      enabled: '#5AAC90',
      hover: '#4A9A7E',
      active: '#3D8A6E',
      important: {
        enabled: '#F06E7A',
        hover: '#E05565',
        active: '#D04050',
      },
      monochrome: {
        onLight: {
          enabled: 'rgba(255, 255, 255, 0.70)',
          hover: 'rgba(255, 255, 255, 0.85)',
          active: 'rgba(255, 255, 255, 1)',
          selected: 'rgba(255, 255, 255, 1)',
          disabled: 'rgba(255, 255, 255, 0.20)',
          bg: 'rgba(255, 255, 255, 0.08)',
          lowEmphasis: {
            enabled: 'rgba(255, 255, 255, 0.55)',
          },
        },
        onDark: {
          enabled: 'rgba(255, 255, 255, 0.94)',
          hover: 'rgba(255, 255, 255, 1)',
          active: 'rgba(255, 255, 255, 1)',
          selected: 'rgba(255, 255, 255, 1)',
          disabled: 'rgba(255, 255, 255, 0.20)',
          bg: 'rgba(255, 255, 255, 0.09)',
          lowEmphasis: {
            enabled: 'rgba(255, 255, 255, 0.65)',
          },
        },
      },
    },

    status: {
      info: '#5B9BD5',
      info_onDark: 'rgba(60, 120, 180, 0.25)',
      success: '#5AAC90',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#E89D3E',
      warningLight: '#6E4A1A',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#F06E7A',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    badge: {
      info: '#5B9BD5',
      infoLight: 'rgba(91, 155, 213, 0.18)',
      success: '#5AAC90',
      successLight: 'rgba(90, 172, 144, 0.18)',
      warning: '#E89D3E',
      warningLight: 'rgba(232, 157, 62, 0.18)',
      important: '#F06E7A',
      importantLight: 'rgba(240, 110, 122, 0.18)',
      aqua: '#3BB8CC',
      aquaLight: 'rgba(59, 184, 204, 0.18)',
      green: '#6BBF4A',
      greenLight: 'rgba(107, 191, 74, 0.18)',
      yellow: '#D4A017',
      yellowLight: 'rgba(212, 160, 23, 0.18)',
      fuschia: '#E060D0',
      fuschiaLight: 'rgba(224, 96, 208, 0.18)',
      purple: '#B87AEF',
      purpleLight: 'rgba(184, 122, 239, 0.18)',
      charcoal: '#A0A0A0',
      charcoalLight: 'rgba(160, 160, 160, 0.18)',
    },

    avatar: {
      '01': '#D6EAFF',
      '02': '#FFDBFA',
      '03': '#EFE0FF',
      '04': '#CFEFC2',
      '05': '#BEF4ED',
      '06': '#FFE68F',
      '07': '#FFE3DB',
      '08': '#FFE2C2',
    },

    dataViz: {
      border: '#FFFFFF',
      '01': '#5AAC90',
      '02': '#4A9A7E',
      '03': '#3D8A6E',
      '04': '#6EC4A4',
      '05': '#8DD4B8',
      '06': '#D4A017',
      '07': '#E0B840',
      '08': '#E8CC66',
      '09': '#5B9BD5',
      '10': '#7BB3E0',
      '11': '#9BCBEB',
      '12': '#F06E7A',
      '13': '#E89D3E',
      '14': '#B87AEF',
      '15': '#3BB8CC',
    },

    cvd: {
      blue: '#0072B2',
      lightBlue: '#56B4E9',
      yellow: '#F0E442',
      green: '#009E73',
      orange: '#E69F00',
      vermillion: '#D55E00',
      pink: '#CC79A7',
      charcoal: '#E0E0E0',
    },

    hover: {
      onLight: 'rgba(255, 255, 255, 0.08)',
      onDark: 'rgba(255, 255, 255, 0.15)',
    },

    selected: {
      onLight: 'rgba(255, 255, 255, 0.12)',
    },

    selectedHighlight: 'rgba(90, 172, 144, 0.15)',
    selectedHighlight_hover: 'rgba(90, 172, 144, 0.25)',

    focusBorder: {
      onLight: '#5AAC90',
      onDark: 'rgba(255, 255, 255, 0.65)',
    },

    scrim: 'rgba(0, 0, 0, 0.50)',

    scrollbar: {
      enabled: { onLight: '#606060', onDark: 'rgba(255, 255, 255, 0.43)' },
      hover: { onLight: '#787878', onDark: 'rgba(255, 255, 255, 0.58)' },
      active: { onLight: '#909090', onDark: 'rgba(255, 255, 255, 0.73)' },
    },

    navItemText: {
      enabled: { onLight: 'rgba(255, 255, 255, 0.72)', onDark: 'rgba(255, 255, 255, 0.88)' },
    },

    buttonToggleBg: {
      onLight: 'rgba(255, 255, 255, 0.08)',
      onDark: 'rgba(255, 255, 255, 0.08)',
    },

    chipBg: {
      enabled: 'rgba(255, 255, 255, 0.08)',
      hover: 'rgba(255, 255, 255, 0.13)',
    },

    progressIndicatorTrack: 'rgba(255, 255, 255, 0.15)',

    tableCellHighlight: {
      highEmphasis: '#5AAC90',
      midEmphasis: 'rgba(90, 172, 144, 0.20)',
    },

    grid: {
      finishedRowText: '#A1A1A1',
      packageIconColor: '#A1A1A1',
    },
  },

  // ===========================================================================
  // TYPOGRAPHY — Modern: Inter (matches RID light theme)
  // ===========================================================================
  typography: {
    fontFamilies: {
      display: 'var(--font-inter), sans-serif',
      body: 'var(--font-inter), sans-serif',
      mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontWeights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    scale: {
      lineHeightTight: '1.2',
      lineHeightNormal: '1.5',
      letterSpacingHeading: '-0.3px',
      letterSpacingBody: '0px',
    },
  },

  // ===========================================================================
  // BORDER RADIUS — base: 2px (identical to RID)
  // ===========================================================================
  borderRadius: buildBorderRadius(2),

  // ===========================================================================
  // ELEVATION — Pure black shadows for dark context depth
  // ===========================================================================
  elevation: {
    none: 'none',
    xs: '0px 1px 2px rgba(0, 0, 0, 0.20)',
    sm: '0px 1px 3px rgba(0, 0, 0, 0.30), 0px 1px 2px rgba(0, 0, 0, 0.24)',
    md: '0px 4px 6px -1px rgba(0, 0, 0, 0.30), 0px 2px 4px -1px rgba(0, 0, 0, 0.24)',
    lg: '0px 10px 15px -3px rgba(0, 0, 0, 0.30), 0px 4px 6px -2px rgba(0, 0, 0, 0.20)',
    xl: '0px 20px 25px -5px rgba(0, 0, 0, 0.35), 0px 10px 10px -5px rgba(0, 0, 0, 0.20)',
    '2xl': '0px 25px 50px -12px rgba(0, 0, 0, 0.50)',
    inner: 'inset 0px 2px 4px rgba(0, 0, 0, 0.25)',
    brand: '0px 4px 14px rgba(0, 0, 0, 0.35)',
    brandLg: '0px 10px 25px rgba(0, 0, 0, 0.45)',
  },

  // ===========================================================================
  // SPACING — Enterprise: standard, structured
  // ===========================================================================
  spacing: {
    unit: '4px',
    inputPadding: '12px',
    buttonPadding: '16px',
    cardPadding: '24px',
    sectionGap: '48px',
    componentGap: '16px',
  },

  // ===========================================================================
  // ICON STYLE — Enterprise: outlined with standard strokes
  // ===========================================================================
  iconStyle: {
    set: 'outlined',
    strokeWidth: '1.5',
    cornerStyle: 'round',
    defaultSize: '20',
    overrides: {},
  },

  // ===========================================================================
  // COMPONENT RADIUS — base: 2, identical to RID (button overridden to sm)
  // ===========================================================================
  componentRadius: buildComponentRadius(2, { button: '4px' }),
};
