/**
 * RID Product Theme
 * Generated by /theme-generator on 2026-03-04
 *
 * Brand color: #213F39 (forest green)
 * Accent strategy: Split-complementary — warm copper (#B87333) at ~192° rotation
 * Personality: Modern — Inter font, moderate radius, standard spacing
 *
 * Differentiators from University theme (same brand color):
 * - Warm copper accent (vs University's gold)
 * - Modern sans-serif Inter (vs University's Playfair Display serif)
 * - Moderate border radius (vs University's sharp/institutional)
 * - Standard spacing (vs University's compact)
 * - Outlined icons (vs University's filled)
 *
 * Design notes:
 * - Links use teal (#007E8A) with underline decoration via text.action tokens
 * - All text-on-surface combos verified WCAG 2.1 AA (≥4.5:1)
 */

import type { ProductTheme } from './theme-interface';
import { buildBorderRadius, buildComponentRadius } from './theme-interface';

export const ridTheme: ProductTheme = {
  name: 'Foliage',
  colors: {
    brand: {
      default: '#213F39',
      darker: '#0D2420',
      lighter: '#3A6058',
    },

    accent: {
      default: '#B87333',
      darker: '#8F5620',
      lighter: '#D49558',
    },

    surface: {
      light: '#F5F7F6',
      lightDarker: 'rgba(0, 0, 0, 0.06)',
      dark: '#33423F',
      darkDarker: '#213F39',
      disabled: {
        onLight: 'rgba(33, 63, 57, 0.03)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      info: '#F0F4F8',
      success: '#EDF6F4',
      warning: '#FCF6ED',
      important: '#FDF2F3',
    },

    surfaceBorder: {
      info: '#C8D5E0',
      success: '#C5E2DB',
      warning: '#F2DABA',
      important: '#F8CFD3',
    },

    text: {
      highEmphasis: {
        onLight: '#191C1B',
        onDark: '#FFFFFF',
      },
      lowEmphasis: {
        onLight: '#4A5552',
        onDark: 'rgba(255, 255, 255, 0.70)',
      },
      disabled: {
        onLight: 'rgba(33, 63, 57, 0.30)',
        onDark: 'rgba(255, 255, 255, 0.30)',
      },
      action: {
        enabled: '#007E8A',
        hover: '#006370',
        active: '#004A55',
      },
      success: '#006B50',
      warning: '#A35C00',
      important: '#C10B1E',
    },

    border: {
      lowEmphasis: {
        onLight: 'rgba(33, 63, 57, 0.10)',
        onDark: 'rgba(255, 255, 255, 0.10)',
        hover: {
          onLight: 'rgba(33, 63, 57, 0.27)',
          onDark: 'rgba(255, 255, 255, 0.27)',
        },
      },
      midEmphasis: {
        onLight: 'rgba(33, 63, 57, 0.15)',
        onDark: 'rgba(255, 255, 255, 0.15)',
      },
      highEmphasis: {
        onLight: 'rgba(33, 63, 57, 0.42)',
        onDark: 'rgba(255, 255, 255, 0.43)',
      },
    },

    icon: {
      enabled: {
        onLight: 'rgba(33, 63, 57, 0.55)',
        onDark: 'rgba(255, 255, 255, 0.94)',
      },
      hover: {
        onLight: 'rgba(33, 63, 57, 0.65)',
      },
      active: {
        onLight: 'rgba(33, 63, 57, 0.75)',
      },
      selected: {
        onLight: 'rgba(33, 63, 57, 0.85)',
      },
      disabled: {
        onLight: 'rgba(33, 63, 57, 0.20)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      lowEmphasis: {
        enabled: {
          onLight: 'rgba(33, 63, 57, 0.43)',
          onDark: 'rgba(255, 255, 255, 0.65)',
        },
      },
    },

    iconBg: {
      info: '#E0EAF0',
      info_onDark: 'rgba(60, 120, 180, 0.25)',
      success: '#DEEDE9',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#F9ECDC',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#FBE4E7',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    action: {
      enabled: '#213F39',
      hover: '#0D2420',
      active: '#0D2420',
      important: {
        enabled: '#C10B1E',
        hover: '#A20919',
        active: '#850715',
      },
      monochrome: {
        onLight: {
          enabled: 'rgba(0, 0, 0, 0.55)',
          hover: 'rgba(0, 0, 0, 0.65)',
          active: 'rgba(0, 0, 0, 0.75)',
          selected: 'rgba(0, 0, 0, 0.85)',
          disabled: 'rgba(0, 0, 0, 0.20)',
          bg: 'rgba(0, 0, 0, 0.08)',
          lowEmphasis: {
            enabled: 'rgba(0, 0, 0, 0.43)',
          },
        },
        onDark: {
          enabled: 'rgba(255, 255, 255, 0.94)',
          hover: 'rgba(255, 255, 255, 1)',
          active: 'rgba(255, 255, 255, 1)',
          selected: 'rgba(255, 255, 255, 1)',
          disabled: 'rgba(255, 255, 255, 0.20)',
          bg: 'rgba(255, 255, 255, 0.09)',
          lowEmphasis: {
            enabled: 'rgba(255, 255, 255, 0.65)',
          },
        },
      },
    },

    status: {
      info: '#3C78B4',
      info_onDark: 'rgba(60, 120, 180, 0.25)',
      success: '#1B7F66',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#CC7300',
      warningLight: '#F3DCBD',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#DC0C22',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    badge: {
      info: '#3C78B4',
      infoLight: '#DBE8F4',
      success: '#19856B',
      successLight: '#D9EDE6',
      warning: '#AD6200',
      warningLight: '#FCF6ED',
      important: '#E80D24',
      importantLight: '#FFE3E7',
      aqua: '#167F92',
      aquaLight: '#B4EAF3',
      green: '#40851E',
      greenLight: '#DAF4CD',
      yellow: '#8F6F00',
      yellowLight: '#FFE68F',
      fuschia: '#CF26B8',
      fuschiaLight: '#FCCFF6',
      purple: '#A14CE1',
      purpleLight: '#EDDCF9',
      charcoal: '#4A5552',
      charcoalLight: '#DFE3E2',
    },

    avatar: {
      '01': '#D6EAFF',
      '02': '#FFDBFA',
      '03': '#EFE0FF',
      '04': '#CFEFC2',
      '05': '#BEF4ED',
      '06': '#FFE68F',
      '07': '#FFE3DB',
      '08': '#FFE2C2',
    },

    dataViz: {
      border: '#000000',
      '01': '#0D2420',
      '02': '#152E28',
      '03': '#213F39',
      '04': '#2C4E47',
      '05': '#3A6058',
      '06': '#5A7D6B',
      '07': '#8A9E7A',
      '08': '#C0B86E',
      '09': '#B87333',
      '10': '#C68540',
      '11': '#D49558',
      '12': '#E0A870',
      '13': '#3C78B4',
      '14': '#2C5A8A',
      '15': '#1D3D60',
    },

    cvd: {
      blue: '#0072B2',
      lightBlue: '#56B4E9',
      yellow: '#F0E442',
      green: '#009E73',
      orange: '#E69F00',
      vermillion: '#D55E00',
      pink: '#CC79A7',
      charcoal: '#323232',
    },

    hover: {
      onLight: 'rgba(33, 63, 57, 0.05)',
      onDark: 'rgba(255, 255, 255, 0.15)',
    },

    selected: {
      onLight: 'rgba(33, 63, 57, 0.09)',
    },

    selectedHighlight: '#DCE8E5',
    selectedHighlight_hover: '#C5D8D4',

    focusBorder: {
      onLight: '#007E8A',
      onDark: 'rgba(255, 255, 255, 0.65)',
    },

    scrim: 'rgba(33, 63, 57, 0.34)',

    scrollbar: {
      enabled: {
        onLight: 'rgba(33, 63, 57, 0.42)',
        onDark: 'rgba(255, 255, 255, 0.43)',
      },
      hover: {
        onLight: 'rgba(33, 63, 57, 0.57)',
        onDark: 'rgba(255, 255, 255, 0.58)',
      },
      active: {
        onLight: 'rgba(33, 63, 57, 0.72)',
        onDark: 'rgba(255, 255, 255, 0.73)',
      },
    },

    navItemText: {
      enabled: {
        onLight: 'rgba(33, 63, 57, 0.72)',
        onDark: 'rgba(255, 255, 255, 0.88)',
      },
    },

    buttonToggleBg: {
      onLight: 'rgba(33, 63, 57, 0.08)',
      onDark: 'rgba(255, 255, 255, 0.08)',
    },

    chipBg: {
      enabled: 'rgba(33, 63, 57, 0.08)',
      hover: 'rgba(33, 63, 57, 0.13)',
    },

    progressIndicatorTrack: 'rgba(33, 63, 57, 0.15)',

    tableCellHighlight: {
      highEmphasis: '#5AAE90',
      midEmphasis: '#DCE8E5',
    },

    grid: {
      finishedRowText: '#5A6562',
      packageIconColor: '#5A6562',
    },
  },

  // ===========================================================================
  // TYPOGRAPHY — Modern: Inter for both headings and body
  // ===========================================================================
  typography: {
    fontFamilies: {
      display: 'var(--font-inter), sans-serif',
      body: 'var(--font-inter), sans-serif',
      mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontWeights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    scale: {
      lineHeightTight: '1.2',
      lineHeightNormal: '1.5',
      letterSpacingHeading: '-0.5px',
      letterSpacingBody: '0px',
    },
  },

  // ===========================================================================
  // BORDER RADIUS — base: 2px (smallest baseline)
  // ===========================================================================
  borderRadius: buildBorderRadius(2),

  // ===========================================================================
  // ELEVATION — Forest green tinted shadows (brand RGB: 33, 63, 57)
  // ===========================================================================
  elevation: {
    none: 'none',
    xs: '0px 1px 2px rgba(33, 63, 57, 0.06)',
    sm: '0px 1px 3px rgba(33, 63, 57, 0.10), 0px 1px 2px rgba(33, 63, 57, 0.08)',
    md: '0px 4px 6px -1px rgba(33, 63, 57, 0.10), 0px 2px 4px -1px rgba(33, 63, 57, 0.08)',
    lg: '0px 10px 15px -3px rgba(33, 63, 57, 0.10), 0px 4px 6px -2px rgba(33, 63, 57, 0.06)',
    xl: '0px 20px 25px -5px rgba(33, 63, 57, 0.12), 0px 10px 10px -5px rgba(33, 63, 57, 0.06)',
    '2xl': '0px 25px 50px -12px rgba(33, 63, 57, 0.28)',
    inner: 'inset 0px 2px 4px rgba(33, 63, 57, 0.08)',
    brand: '0px 4px 14px rgba(33, 63, 57, 0.25)',
    brandLg: '0px 10px 25px rgba(33, 63, 57, 0.30)',
  },

  // ===========================================================================
  // SPACING — Modern: standard, balanced
  // ===========================================================================
  spacing: {
    unit: '4px',
    inputPadding: '12px',
    buttonPadding: '16px',
    cardPadding: '24px',
    sectionGap: '48px',
    componentGap: '16px',
  },

  // ===========================================================================
  // ICON STYLE — Modern: outlined with standard strokes
  // ===========================================================================
  iconStyle: {
    set: 'outlined',
    strokeWidth: '1.5',
    cornerStyle: 'round',
    defaultSize: '20',
    overrides: {},
  },

  // ===========================================================================
  // COMPONENT RADIUS — base: 2, button overridden to match sm (2×2 = 4px)
  // ===========================================================================
  componentRadius: buildComponentRadius(2, { button: '4px' }),
};
