/**
 * University Product Theme
 * Generated by Prism Theme Playground on 2026-04-02
 * Brand color: #385C3F
 */

import type { ProductTheme } from './theme-interface';
import { buildBorderRadius, buildComponentRadius } from './theme-interface';

export const universityTheme: ProductTheme = {
  name: 'Spring',
  colors: {
    brand: {
      default: '#385C3F',
      darker: '#1F3524',
      lighter: '#5A7E61',
    },

    accent: {
      default: '#D4B85C',
      darker: '#B09538',
      lighter: '#E2CC7E',
    },

    surface: {
      light: '#F7F9F7',
      lightDarker: '#EEF0EE',
      dark: '#3E4F42',
      darkDarker: '#2A3B2E',
      disabled: {
        onLight: 'rgba(0, 0, 0, 0.03)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      info: '#F0F5F1',
      success: '#EDF6F0',
      warning: '#FCF6ED',
      important: '#FDF2F3',
    },

    surfaceBorder: {
      info: '#C3CEC6',
      success: '#C5E2CE',
      warning: '#F2DABA',
      important: '#F8CFD3',
    },

    text: {
      highEmphasis: {
        onLight: '#191C1A',
        onDark: '#FFFFFF',
      },
      lowEmphasis: {
        onLight: '#4F5553',
        onDark: 'rgba(255, 255, 255, 0.70)',
      },
      disabled: {
        onLight: 'rgba(0, 0, 0, 0.30)',
        onDark: 'rgba(255, 255, 255, 0.30)',
      },
      action: {
        enabled: '#385C3F',
        hover: '#1F3524',
        active: '#1F3524',
      },
      success: '#006B50',
      warning: '#A35C00',
      important: '#C10B1E',
    },

    border: {
      lowEmphasis: {
        onLight: '#DCDFDD',
        onDark: 'rgba(255, 255, 255, 0.10)',
        hover: {
          onLight: 'rgba(0, 0, 0, 0.27)',
          onDark: 'rgba(255, 255, 255, 0.27)',
        },
      },
      midEmphasis: {
        onLight: '#C3CEC6',
        onDark: 'rgba(255, 255, 255, 0.15)',
      },
      highEmphasis: {
        onLight: 'rgba(0, 0, 0, 0.42)',
        onDark: 'rgba(255, 255, 255, 0.43)',
      },
    },

    icon: {
      enabled: {
        onLight: '#436E4A',
        onDark: 'rgba(255, 255, 255, 0.94)',
      },
      hover: {
        onLight: '#385C3F',
      },
      active: {
        onLight: '#1F3524',
      },
      selected: {
        onLight: '#1F3524',
      },
      disabled: {
        onLight: 'rgba(0, 0, 0, 0.20)',
        onDark: 'rgba(255, 255, 255, 0.20)',
      },
      lowEmphasis: {
        enabled: {
          onLight: '#4F5553',
          onDark: 'rgba(255, 255, 255, 0.65)',
        },
      },
    },

    iconBg: {
      info: '#DDE8DF',
      info_onDark: 'rgba(56, 92, 63, 0.25)',
      success: '#DEEDE2',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#F9ECDC',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#FBE4E7',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    action: {
      enabled: '#385C3F',
      hover: '#1F3524',
      active: '#1F3524',
      important: {
        enabled: '#C10B1E',
        hover: '#A20919',
        active: '#850715',
      },
      monochrome: {
        onLight: {
          enabled: 'rgba(0, 0, 0, 0.55)',
          hover: 'rgba(0, 0, 0, 0.65)',
          active: 'rgba(0, 0, 0, 0.75)',
          selected: 'rgba(0, 0, 0, 0.85)',
          disabled: 'rgba(0, 0, 0, 0.20)',
          bg: 'rgba(0, 0, 0, 0.08)',
          lowEmphasis: {
            enabled: 'rgba(0, 0, 0, 0.43)',
          },
        },
        onDark: {
          enabled: 'rgba(255, 255, 255, 0.94)',
          hover: 'rgba(255, 255, 255, 1)',
          active: 'rgba(255, 255, 255, 1)',
          selected: 'rgba(255, 255, 255, 1)',
          disabled: 'rgba(255, 255, 255, 0.20)',
          bg: 'rgba(255, 255, 255, 0.09)',
          lowEmphasis: {
            enabled: 'rgba(255, 255, 255, 0.65)',
          },
        },
      },
    },

    status: {
      info: '#4A6E50',
      info_onDark: 'rgba(56, 92, 63, 0.25)',
      success: '#1B7F66',
      success_onDark: 'rgba(0, 173, 130, 0.25)',
      warning: '#CC7300',
      warningLight: '#F3DCBD',
      warning_onDark: 'rgba(230, 130, 0, 0.25)',
      important: '#DC0C22',
      important_onDark: 'rgba(248, 104, 118, 0.25)',
    },

    badge: {
      info: '#385C3F',
      infoLight: '#DDE8DF',
      success: '#19856B',
      successLight: '#D9EDE6',
      warning: '#AD6200',
      warningLight: '#FCF6ED',
      important: '#E80D24',
      importantLight: '#FFE3E7',
      aqua: '#1A8A80',
      aquaLight: '#BBF0EA',
      green: '#2D8A3E',
      greenLight: '#C8EFCC',
      yellow: '#9E8415',
      yellowLight: '#F2E6B0',
      fuschia: '#B0309A',
      fuschiaLight: '#F5CCF0',
      purple: '#7640B8',
      purpleLight: '#E2D3F6',
      charcoal: '#4F5753',
      charcoalLight: '#E0E4E1',
    },

    avatar: {
      '01': '#C8E8CB',
      '02': '#C2E8E2',
      '03': '#C5D6EC',
      '04': '#D8C8ED',
      '05': '#EBC5E2',
      '06': '#ECC5C8',
      '07': '#ECDCC5',
      '08': '#D8ECC5',
    },

    dataViz: {
      border: '#000000',
      '01': '#1A2E1E',
      '02': '#243826',
      '03': '#2E4432',
      '04': '#385C3F',
      '05': '#4A6E50',
      '06': '#5F8566',
      '07': '#7FA387',
      '08': '#B0CBB4',
      '09': '#D4B85C',
      '10': '#BFA348',
      '11': '#A38D37',
      '12': '#8A7628',
      '13': '#6E5E16',
      '14': '#504508',
      '15': '#332D00',
    },

    cvd: {
      blue: '#0072B2',
      lightBlue: '#56B4E9',
      yellow: '#F0E442',
      green: '#009E73',
      orange: '#E69F00',
      vermillion: '#D55E00',
      pink: '#CC79A7',
      charcoal: '#323232',
    },

    hover: {
      onLight: 'rgba(0, 0, 0, 0.05)',
      onDark: 'rgba(255, 255, 255, 0.15)',
    },

    selected: {
      onLight: 'rgba(0, 0, 0, 0.09)',
    },

    selectedHighlight: '#DDE8DF',
    selectedHighlight_hover: '#C6D5C9',

    focusBorder: {
      onLight: '#5A7E61',
      onDark: 'rgba(255, 255, 255, 0.65)',
    },

    scrim: 'rgba(0, 0, 0, 0.32)',

    scrollbar: {
      enabled: {
        onLight: 'rgba(0, 0, 0, 0.42)',
        onDark: 'rgba(255, 255, 255, 0.43)',
      },
      hover: {
        onLight: 'rgba(0, 0, 0, 0.57)',
        onDark: 'rgba(255, 255, 255, 0.58)',
      },
      active: {
        onLight: 'rgba(0, 0, 0, 0.72)',
        onDark: 'rgba(255, 255, 255, 0.73)',
      },
    },

    navItemText: {
      enabled: {
        onLight: '#436E4A',
        onDark: 'rgba(255, 255, 255, 0.88)',
      },
    },

    buttonToggleBg: {
      onLight: '#DDE8DF',
      onDark: 'rgba(255, 255, 255, 0.08)',
    },

    chipBg: {
      enabled: '#DDE8DF',
      hover: '#C6D5C9',
    },

    progressIndicatorTrack: 'rgba(0, 0, 0, 0.15)',

    tableCellHighlight: {
      highEmphasis: '#78CF8E',
      midEmphasis: '#DDE8DF',
    },

    grid: {
      finishedRowText: '#595959',
      packageIconColor: '#595959',
    },
  },

  typography: {
    fontFamilies: {
      display: 'var(--font-inter), "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
      body: 'var(--font-inter), "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
      mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontWeights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    scale: {
      lineHeightTight: '1.2',
      lineHeightNormal: '1.5',
      letterSpacingHeading: '-0.5px',
      letterSpacingBody: '0px',
    },
  },

  borderRadius: buildBorderRadius(1),

  elevation: {
    none: 'none',
    xs: '0px 1px 2px rgba(0,0,0,0.05)',
    sm: '0px 1px 3px rgba(0,0,0,0.1)',
    md: '0px 4px 6px -1px rgba(0,0,0,0.1)',
    lg: '0px 10px 15px -3px rgba(0,0,0,0.1)',
    xl: '0px 20px 25px -5px rgba(0,0,0,0.1)',
    '2xl': '0px 25px 50px -12px rgba(0,0,0,0.25)',
    inner: 'inset 0px 2px 4px rgba(0,0,0,0.06)',
    brand: '0px 4px 14px rgba(56,92,63,0.25)',
    brandLg: '0px 10px 25px rgba(56,92,63,0.3)',
  },

  spacing: {
    unit: '4px',
    inputPadding: '10px',
    buttonPadding: '14px',
    cardPadding: '20px',
    sectionGap: '40px',
    componentGap: '12px',
  },

  iconStyle: {
    set: 'filled',
    strokeWidth: '1.5',
    cornerStyle: 'round',
    defaultSize: '20',
    overrides: {},
  },

  componentRadius: buildComponentRadius(1),
};
